export {default as Profile} from "./profile"
export {default as Skills} from "./skills"
export {default as Navbar} from "./Navbar"
export {default as Education} from "./Education"
export {default as Projects} from "./Projects"